<!-- RSS generated by PHPBoost on <?php echo isset($this->_var['DATE']) ? $this->_var['DATE'] : ''; ?> -->

<rss version="2.0">
	<channel>
		<title><?php echo isset($this->_var['TITLE_RSS']) ? $this->_var['TITLE_RSS'] : ''; ?></title>
		<link><?php echo isset($this->_var['HOST']) ? $this->_var['HOST'] : ''; ?></link>
		<description><?php echo isset($this->_var['DESC']) ? $this->_var['DESC'] : ''; ?></description>
		<copyright>© 2005-2006 PHPBoost</copyright>
		<language><?php echo isset($this->_var['LANG']) ? $this->_var['LANG'] : ''; ?></language>
		<generator>PHPBoost</generator>

		<?php if( !isset($this->_block['rss']) || !is_array($this->_block['rss']) ) $this->_block['rss'] = array();
foreach($this->_block['rss'] as $rss_key => $rss_value) {
$_tmpb_rss = &$this->_block['rss'][$rss_key]; ?>
		<item>
			<title><?php echo isset($_tmpb_rss['TITLE']) ? $_tmpb_rss['TITLE'] : ''; ?></title>
			<link><?php echo isset($_tmpb_rss['LINK']) ? $_tmpb_rss['LINK'] : ''; ?></link>
			<description><?php echo isset($_tmpb_rss['DESC']) ? $_tmpb_rss['DESC'] : ''; ?></description>
			<pubDate><?php echo isset($_tmpb_rss['DATE']) ? $_tmpb_rss['DATE'] : ''; ?></pubDate>
		</item>		
		<?php } ?>
		
	</channel> 
</rss>