tinyMCE.addI18n('fr.emotions_dlg',{
title:"Insérez les smileys",
desc:"Smileys",
cool:"Cool",
cry:"Pleure",
embarassed:"Embarassé",
foot_in_mouth:"Foot in mouth",
frown:"Frown",
innocent:"Innocent",
kiss:"Kiss",
laughing:"Laughing",
money_mouth:"Money mouth",
sealed:"Sealed",
smile:"Smile",
surprised:"Surprised",
tongue_out:"Tongue out",
undecided:"Undecided",
wink:"Wink",
yell:"Yell"
});