<?php
/*##################################################
 *                              AdminServerSystemReportController.class.php
 *                            -------------------
 *   begin                : May 20, 2015
 *   copyright            : (C) 2015 Julien BRISWALTER
 *   email                : julienseth78@phpboost.com
 *
 *  
 ###################################################
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
 *
 ###################################################*/

class AdminServerSystemReportController extends AdminController
{
	private $lang;
	private $admin_lang;
	private $form;
	private $tpl;

	public function execute(HTTPRequestCustom $request)
	{
		$this->init();
		
		$this->build_form();

		$this->tpl->put('FORM', $this->form->display());
		
		return new AdminServerDisplayResponse($this->tpl, $this->admin_lang['system_report']);
	}

	private function init()
	{
		$this->lang = LangLoader::get('admin-server-common');
		$this->admin_lang = LangLoader::get('admin');
		$this->tpl = new StringTemplate('# INCLUDE FORM #');
		$this->tpl->add_lang($this->admin_lang);
	}

	private function build_form()
	{
		$picture_yes = '<i class="fa fa-success fa-2x" title="' . LangLoader::get_message('yes', 'common') . '"></i>';
		$picture_no = '<i class="fa fa-error fa-2x" title="' . LangLoader::get_message('no', 'common') . '"></i>';
		$picture_unknown = '<i class="fa fa-question fa-2x" title="' . LangLoader::get_message('unknown', 'main') . '"></i>';
		
		$user = AppContext::get_current_user();
		$lang_ini_file = load_ini_file(PATH_TO_ROOT .'/lang/', $user->get_locale());
		$template_ini_file = @parse_ini_file(PATH_TO_ROOT .'/templates/' . $user->get_theme() . '/lang/' . $user->get_locale() . '/desc.ini');
		$editors = AppContext::get_content_formatting_service()->get_available_editors();
		$default_editor = $editors[ContentFormattingConfig::load()->get_default_editor()];
		$server_configuration = new ServerConfiguration();
		$general_config = GeneralConfig::load();
		$server_environment_config = ServerEnvironmentConfig::load();
		$sessions_config = SessionsConfig::load();
		$maintenance_config = MaintenanceConfig::load();
		
		$url_rewriting_available = false;
		$url_rewriting_known = true;

		try
		{
			$url_rewriting_available = $server_configuration->has_url_rewriting();
		}
		catch (UnsupportedOperationException $ex)
		{
			$url_rewriting_known = false;
		}

		$summerization =
"---------------------------------System report---------------------------------
-----------------------------generated by PHPBoost-----------------------------
SERVER CONFIGURATION-----------------------------------------------------------
php version              : " . ServerConfiguration::get_phpversion() . "
dbms version             : " . PersistenceContext::get_dbms_utils()->get_dbms_version() . "
gd library               : " . (int)$server_configuration->has_gd_library() . "
url rewriting            : " . ($url_rewriting_known ? (int) $url_rewriting_available : 'N/A') . "
apcu cache               : " . (int) DataStoreFactory::is_apc_available() . "
PHPBOOST CONFIGURATION---------------------------------------------------------
phpboost version         : " . Environment::get_phpboost_version() . "
server url               : " . $general_config->get_site_url() . "
site path                : " . $general_config->get_site_path()  . "
default theme            : " . $template_ini_file['name'] . "
default language         : " . $lang_ini_file['name'] . "
default editor           : " . $default_editor . "
home page                : " . Environment::get_home_page() . "
url rewriting            : " . (int)$server_environment_config->is_url_rewriting_enabled() . "
apcu cache               : " . (int) DataStoreFactory::is_apc_enabled() . "
output gzip              : " . (int)$server_environment_config->is_output_gziping_enabled() . "
session cookie name      : " . $sessions_config->get_cookie_name() . "
session duration         : " . $sessions_config->get_session_duration() . "
active session duration  : " . $sessions_config->get_active_session_duration() . "
DIRECTORIES AUTHORIZATIONS-----------------------------------------------------
";

		$form = new HTMLForm('system-report', '', false);
		$fieldset = new FormFieldsetHTML('advises', $this->lang['advises']);
		$form->add_fieldset($fieldset);
		
		$fieldset->add_field(new FormFieldFree('modules_management', '', MessageHelper::display($this->lang['advises.modules_management'], MessageHelper::SUCCESS)->render()));
		
		if ($maintenance_config->is_under_maintenance())
			$fieldset->add_field(new FormFieldFree('check_modules_authorizations', '', MessageHelper::display($this->lang['advises.check_modules_authorizations'], MessageHelper::SUCCESS)->render()));
		
		if (!strstr($general_config->get_site_url(), 'localhost') && !strstr($general_config->get_site_url(), '127.0.0.1') && !$maintenance_config->is_under_maintenance() && Debug::is_debug_mode_enabled())
			$fieldset->add_field(new FormFieldFree('disable_debug_mode', '', MessageHelper::display($this->lang['advises.disable_debug_mode'], MessageHelper::WARNING)->render()));
		
		if ($url_rewriting_available && !$server_environment_config->is_url_rewriting_enabled())
			$fieldset->add_field(new FormFieldFree('enable_url_rewriting', '', MessageHelper::display($this->lang['advises.enable_url_rewriting'], MessageHelper::NOTICE)->render()));
		
		if (function_exists('ob_gzhandler') && @extension_loaded('zlib') && !$server_environment_config->is_output_gziping_enabled())
			$fieldset->add_field(new FormFieldFree('enable_output_gz', '', MessageHelper::display($this->lang['advises.enable_output_gz'], MessageHelper::NOTICE)->render()));
		
		if (DataStoreFactory::is_apc_available() && !DataStoreFactory::is_apc_enabled())
			$fieldset->add_field(new FormFieldFree('enable_apcu_cache', '', MessageHelper::display($this->lang['advises.enable_apcu_cache'], MessageHelper::NOTICE)->render()));
		
		if (ServerConfiguration::get_phpversion() < '5.6')
			$fieldset->add_field(new FormFieldFree('upgrade_php_version', '', MessageHelper::display($this->lang['advises.upgrade_php_version'], MessageHelper::NOTICE)->render()));
		
		$fieldset->add_field(new FormFieldFree('optimize_database_tables', '', MessageHelper::display($this->lang['advises.optimize_database_tables'], MessageHelper::SUCCESS)->render()));
		
		$fieldset = new FormFieldsetHTML('report', $this->admin_lang['server']);
		$form->add_fieldset($fieldset);
		
		$fieldset->add_field(new FormFieldFree('php_version', $this->admin_lang['php_version'], ServerConfiguration::get_phpversion()));
		$fieldset->add_field(new FormFieldFree('dbms_version', $this->admin_lang['dbms_version'], PersistenceContext::get_dbms_utils()->get_dbms_version()));
		$fieldset->add_field(new FormFieldFree('gd_library', $this->admin_lang['gd_library'], $server_configuration->has_gd_library() ? $picture_yes : $picture_no));
		$fieldset->add_field(new FormFieldFree('url_rewriting', $this->admin_lang['url_rewriting'], $url_rewriting_known ? ($url_rewriting_available ? $picture_yes : $picture_no) : $picture_unknown));
		$fieldset->add_field(new FormFieldFree('apcu_cache', LangLoader::get_message('apcu_cache', 'admin-cache-common'), DataStoreFactory::is_apc_available() ? $picture_yes : $picture_no));

		$fieldset = new FormFieldsetHTML('report', $this->admin_lang['phpboost_config']);
		$form->add_fieldset($fieldset);
		
		$fieldset->add_field(new FormFieldFree('kernel_version', $this->admin_lang['kernel_version'], Environment::get_phpboost_version()));
		$fieldset->add_field(new FormFieldFree('site_url', LangLoader::get_message('advanced-config.site_url', 'admin-config-common'), $general_config->get_site_url()));
		$fieldset->add_field(new FormFieldFree('site_path', LangLoader::get_message('advanced-config.site_path', 'admin-config-common'), $general_config->get_site_path()));
		$fieldset->add_field(new FormFieldFree('default_theme', LangLoader::get_message('general-config.default_theme', 'admin-config-common'), $template_ini_file['name']));
		$fieldset->add_field(new FormFieldFree('default_language', LangLoader::get_message('general-config.default_language', 'admin-config-common'), $lang_ini_file['name']));
		$fieldset->add_field(new FormFieldFree('default_editor', LangLoader::get_message('content.config.default-formatting-language', 'admin-contents-common'), $default_editor));
		$fieldset->add_field(new FormFieldFree('start_page', LangLoader::get_message('general-config.start_page', 'admin-config-common'), Environment::get_home_page()));
		$fieldset->add_field(new FormFieldFree('phpboost_url_rewriting', $this->admin_lang['url_rewriting'], $server_environment_config->is_url_rewriting_enabled() ? $picture_yes : $picture_no));
		$fieldset->add_field(new FormFieldFree('phpboost_apcu_cache', LangLoader::get_message('apcu_cache', 'admin-cache-common'), DataStoreFactory::is_apc_enabled() ? $picture_yes : $picture_no));
		$fieldset->add_field(new FormFieldFree('output_gz', $this->admin_lang['output_gz'], $server_environment_config->is_output_gziping_enabled() ? $picture_yes : $picture_no));
		$fieldset->add_field(new FormFieldFree('cookie_name', LangLoader::get_message('advanced-config.cookie-name', 'admin-config-common'), $sessions_config->get_cookie_name()));
		$fieldset->add_field(new FormFieldFree('session_length', LangLoader::get_message('advanced-config.cookie-duration', 'admin-config-common'), $sessions_config->get_session_duration()));
		$fieldset->add_field(new FormFieldFree('session_guest_length', LangLoader::get_message('advanced-config.active-session-duration', 'admin-config-common'), $sessions_config->get_active_session_duration()));
		
		$fieldset = new FormFieldsetHTML('directories_auth', $this->admin_lang['directories_auth']);
		$form->add_fieldset($fieldset);

		$directories_summerization = '';
		foreach (PHPBoostFoldersPermissions::get_permissions() as $key => $folder)
		{
			$fieldset->add_field(new FormFieldFree($key, $key, $folder->is_writable() ? $picture_yes : $picture_no));
			$directories_summerization .= $key . str_repeat(' ', 25 - strlen($key)) . ": " . (int)($folder->is_writable()) . "
";
		}
		
		$fieldset = new FormFieldsetHTML('summerization', $this->admin_lang['system_report_summerization']);
		$form->add_fieldset($fieldset);

		$fieldset->add_field(new FormFieldLabel($this->admin_lang['system_report_summerization_explain']));
		$fieldset->add_field(new FormFieldMultiLineTextEditor('summerization', '', $summerization . $directories_summerization,
			array('rows' => 20, 'cols' => 15, 'class' => 'system-report')
		));
		
		$this->form = $form;
	}
}
?>
