<?php echo '<?xml version="1.0" encoding="ISO-8859-1" ?>'; ?>
<!-- RSS generated by PHPBoost on {DATE} -->

<feed xmlns="http://www.w3.org/2005/Atom">
    <title>{TITLE}</title>
    <subtitle>{SUBTITLE}</subtitle>
    <link href="{HOST}"/>
    <updated>{DATE}</updated>
    <author>
        <name>PHPBoost</name>
        <email>feed@phpboost.com</email>
    </author>
    <id>urn:uuid:60a76c80-d399-11d9-b91C-0003939e0af6</id>
    
    # START atom #
    <entry>
        <title>{atom.TITLE}</title>
        <link href="{atom.LINK}"/>
        <id>urn:uuid:60a76c80-d399-11d9-b91C-0003939e0af6</id>
        <updated>{atom.DATE}</updated>
        <summary>{atom.DESC}</summary>
    </entry>
    # END atom #
    
</feed>

