<?xml version="1.0" encoding="ISO-8859-1" ?>
<!-- RSS generated by PHPBoost on {DATE} -->

<rss version="2.0">
    <channel>
        <title>{TITLE}</title>
        <link>{HOST}</link>
        <description>{DESC}</description>
        <copyright>&copy; 2005-2008 PHPBoost</copyright>
        <language>{LANG}</language>
        <generator>PHPBoost</generator>
        
        # START item #
        <item>
            <title>{item.TITLE}</title>
            <link>{item.LINK}</link>
            <description>{item.DESC}</description>
            <pubDate>{item.DATE}</pubDate>
        </item>
        # END item #
        
    </channel>
</rss>