<?php
/*##################################################
 *                              rss.class.php
 *                            -------------------
 *   begin                : March 10, 2005
 *   copyright            : (C) 2005 Régis Viarre, Loïc Rouchon
 *   email                : crowkait@phpboost.com, horn@phpboost.com
 *
 *
###################################################
 *
 *   This program is free software; you can redistribute it and/or modify
 *   it under the terms of the GNU General Public License as published by
 *   the Free Software Foundation; either version 2 of the License, or
 *   (at your option) any later version.
 * 
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with this program; if not, write to the Free Software
 *  Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
 *
###################################################*/

define('DEFAULT_RSS_TEMPLATE', 'framework/syndication/rss.tpl');

require_once(PATH_TO_ROOT . '/kernel/framework/syndication/feed.class.php');

class RSS extends Feed
{
    ## Public Methods ##
    function RSS($feedName, $feedPath = FEED_PATH)
    /**
     * Constructor
     */
    {
        parent::Feed($feedName, $feedPath, 'rss');
    }

    function parse($nbItems = 5)
    /**
     * Parse the feed contained in the file /<$feedPath>/<$feedName>.rss or
     * /<$feedPath>/<$feedName>.atom if the rss one does not exist et return
     * the result as an Array and <false> if it couldn't open the feed.
     */
    {
        $file = @file_get_contents_emulate($this->path . $this->name . '.rss');
        if( $file !== false )
        {
            if( preg_match('`<item>(.*)</item>`is', $file) )
            {
                $expParsed = explode('<item>', $file);
                $nbItems = (count($expParsed) - 1) > $nbItems ? $nbItems : count($expParsed) - 1;

                $parsed = array();
                $parsed['date'] = preg_match('`<!-- RSS generated by PHPBoost on (.*) -->`is', $expParsed[0], $var) ? $var[1] : '';
                $parsed['title'] = preg_match('`<title>(.*)</title>`is', $expParsed[0], $var) ? $var[1] : '';
                $parsed['link'] = preg_match('`<atom:link href="(.*)" rel="self" type="application/rss+xml" />`is', $expParsed[0], $var) ? $var[1] : '';
                $parsed['host'] = preg_match('`<link>(.*)</link>`is', $expParsed[0], $var) ? $var[1] : '';
                $parsed['desc'] = preg_match('`<description>(.*)</description>`is', $expParsed[0], $var) ? $var[1] : '';
                $parsed['lang'] = preg_match('`<language>(.*)</language>`is', $expParsed[0], $var) ? $var[1] : '';
                $parsed['items'] = array();

                for($i = 1; $i <= $nbItems; $i++)
                {
                    $title = preg_match('`<title>(.*)</title>`is', $expParsed[$i], $title) ? $title[1] : '';
                    $url = preg_match('`<link>(.*)</link>`is', $expParsed[$i], $url) ? $url[1] : '';
                    $guid = preg_match('`<guid>(.*)</guid>`is', $expParsed[$i], $guid) ? $guid[1] : '';
                    $desc = preg_match('`<desc>(.*)</desc>`is', $expParsed[$i], $desc) ? $desc[1] : '';
                    $date = preg_match('`<pubDate>(.*)</pubDate>`is', $expParsed[$i], $date) ? gmdate_format('date_format_tiny', strtotime($date[1])) : '';
                    array_push($parsed['items'], array('title' => $title, 'link' => $url, 'guid' => $guid, 'desc' => $desc, 'date' => $date));

                    unset($parsed['items'][$i]);
                }
                return $parsed;
            }
            return array();
        }
        return false;
    }

    function generate_cache(&$feedInformations)
    /**
     * Generate the feed contained into the files <$feedFile>.rss and <$feedFile>.atom
     * and also the HTML cache for direct includes.
     */
    {
        parent::generate_cache($feedInformations, DEFAULT_RSS_TEMPLATE, '.rss');
    }
    
    ## Private Methods ##
    
    ## Private attributes ##
}

?>