<?xml version="1.0" encoding="ISO-8859-1" ?>
<!-- ATOM generated by PHPBoost on {DATE} -->
<feed xmlns="http://www.w3.org/2005/Atom">
    <title>{TITLE}</title>
    <subtitle>{DESC}</subtitle>
    <link rel="self" type="application/atom+xml" href="{U_LINK}"/>
    <updated>{DATE}</updated>
    <author>
        <name>PHPBoost</name>
        <email>feed@phpboost.com</email>
    </author>
    <id>{U_LINK}</id>
    
    # START item #
    <entry>
        <title>{item.TITLE}</title>
        <link href="{item.U_LINK}"/>
        <id>{item.U_GUID}</id>
        <updated>{item.DATE}</updated>
        <summary>{item.DESC}</summary>
        <!--# IF item.C_IMG #
            <logo>{item.U_IMG}</logo>
        # ENDIF #-->
    </entry>
    # END item #
    
</feed>

