<?php
/*##################################################
 *                                 common.php
 *                            -------------------
 *   begin                : December 23, 2009
 *   copyright            : (C) 2009 Benoit Sautel
 *   email                : ben.popeye@phpboost.com
 *
 *
 ###################################################
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
 *
 ###################################################*/

$lang = array();
$lang['sitemap'] = 'Site map';
$lang['sitemap_xml_could_not_been_written'] = 'The file sitemap.xml generated by the sitemap module could not been written probably due to an authorization problem at the site root.';
$lang['general_config'] = 'General configuration';
$lang['generation_failed'] = 'The sitemap.xml file located at your server\'s root couldn\'t been generated, probably because of a write permission problem.<br /><br />
Please try to create manually and empty sitemap.xml file at you server\'s root and try to generate it again.';
$lang['generation_succeeded'] = 'The sitemap.xml file has been generated sucessfully.';
$lang['try_again'] = 'Try again';
$lang['auto_generate_xml_file'] = 'Generate automatically the sitemap.xml file';
$lang['xml_file_life_time'] = 'sitemap.xml file life time';
$lang['xml_file_life_time_explain'] = 'In days';
$lang['generate_xml_file'] = 'Generate the sitemap.xml file';
?>