<?php
/**
 * @copyright   &copy; 2005-2022 PHPBoost
 * @license     https://www.gnu.org/licenses/gpl-3.0.html GNU/GPL-3.0
 * @author      Benoit SAUTEL <ben.popeye@phpboost.com>
 * @version     PHPBoost 6.0 - last update: 2021 11 21
 * @since       PHPBoost 3.0 - 2009 12 23
 * @contributor Julien BRISWALTER <j1.seth@phpboost.com>
 * @contributor Sebastien LARTIGUE <babsolune@phpboost.com>
*/

#####################################################
#                    English                        #
#####################################################

$lang['sitemap.module.title'] = 'Site map';
$lang['sitemap.generate.xml'] = 'Generate the sitemap.xml file';

$lang['sitemap.warning.xml.authorizations'] = 'The file sitemap.xml generated by the sitemap module could not been written probably due to an authorization problem at the site root.';
$lang['sitemap.try.again']                  = 'Try again';
$lang['sitemap.generation.success']         = 'The sitemap.xml file has been generated sucessfully.';
$lang['sitemap.generation.error'] = '
    The sitemap.xml file located at your server\'s root couldn\'t been generated, probably because of a write permission problem.
    <br /><br />
    Please try to create manually and empty sitemap.xml file at you server\'s root and try to generate it again.
';

$lang['sitemap.auto.generate.xml']  = 'Generate automatically the sitemap.xml file';
$lang['sitemap.xml.life.time']      = 'sitemap.xml file life time';
$lang['sitemap.xml.life.time.clue'] = 'In days';

// S.E.O.
$lang['sitemap.seo.description'] = ':site\'s site map.';
?>
