<?php

$lang = array();
$lang['sitemap'] = 'Site map';
$lang['sitemap_xml_could_not_been_written'] = 'The file sitemap.xml generated by the sitemap module could not been written probably due to an authorization problem at the site root.';

?>